### PR TITLE
Download directory feature

### PR DESCRIPTION
**Pull request by appukuttan-shailesh**
Implements #13 

`name` parameter accepts the name for downloaded zip file.
If not provided, the name of the directory (or repo name in case of root directory) would be used.

Example usage:
```
import ebrains_drive
client = ebrains_drive.connect()
my_repo = client.repos.get_repo_by_url("https://wiki.ebrains.eu/bin/view/Collabs/shailesh-testing")

# download the entire repository
base_dir = my_repo.get_dir('/')
base_dir.download()

# download a directory
my_dir = my_repo.get_dir("/d1/d2/dir2_1")
my_dir.download(name="somename.zip")
```

@lbologna: Could you please test this? (I believe you have a usecase for this feature).

### CODE REVIEW

**Comment by appukuttan-shailesh** [comment]
Thanks @Cracky5457 
I have added the feature to the docs now :+1:

**Comment by lbologna** [comment]
> https://wiki.ebrains.eu/bin/view/Collabs/shailesh-testing

Hello Shailesh,

I tried to test this code:

```
import ebrains_drive
client = ebrains_drive.connect()
my_repo = client.repos.get_repo_by_url("https://wiki.ebrains.eu/bin/view/Collabs/llb-test")

#download the entire repository
base_dir = my_repo.get_dir('/')
base_dir.download()

#download a directory
my_dir = my_repo.get_dir("/CLS-INTERACTIVE-UC/Morphology")
my_dir.download(name="somename.zip")
```


 but I get the following error message:

```
Traceback (most recent call last):
  File "../test.py", line 7, in <module>
    base_dir.download()

  File "/mnt/c/Users/Luca L. Bologna/MyWork/2016_CNR/HBP/sw_hbp/ebrains-drive/venv-ed/lib/python3.8/site-packages/ebrains_drive-0.3.1.dev6+b1290744-py3.8.egg/ebrains_drive/files.py", line 213, in download
    zip_data = self.client.get(url).content

  File "/mnt/c/Users/Luca L. Bologna/MyWork/2016_CNR/HBP/sw_hbp/ebrains-drive/venv-ed/lib/python3.8/site-packages/ebrains_drive-0.3.1.dev6+b1290744-py3.8.egg/ebrains_drive/client.py", line 79, in get
    return self._send_request('GET', *args, **kwargs)

  File "/mnt/c/Users/Luca L. Bologna/MyWork/2016_CNR/HBP/sw_hbp/ebrains-drive/venv-ed/lib/python3.8/site-packages/ebrains_drive-0.3.1.dev6+b1290744-py3.8.egg/ebrains_drive/client.py", line 105, in _send_request
    raise ClientHttpError(resp.status_code, msg)

ebrains_drive.exceptions.ClientHttpError: ClientHttpError[400: Expected 200, but get 400]
```

I made you a member of the above Collab in case you need it.

Best

**Comment by appukuttan-shailesh** [comment]
Thanks for testing this @lbologna 

I do get the same error as you. 
So I tried downloading a sub-directory of this repo from the Collab Drive web interface itself. And apparently the size is too big for this operation to be permiited:
image

I wasn't aware a size restriction exists (and how much it is?!), and we certainly should handle this is in the code to return a meaningful error message. But I suppose the limitation will exist as the API end-point itself doesn't seem to permit download of such large directories.

Could you test for a smaller repo, just to confirm that it works well where this size limit isn't exceeded?

**Comment by appukuttan-shailesh** [comment]
I have now added the error handling for large downloads.

(It would be good to identify from seafile APIs what is the limit for downloads sizes.)

**Comment by lbologna** [comment]
> Thanks for testing this @lbologna
> 
> I do get the same error as you. So I tried downloading a sub-directory of this repo from the Collab Drive web interface itself. And apparently the size is too big for this operation to be permiited: image
> 
> I wasn't aware a size restriction exists (and how much it is?!), and we certainly should handle this is in the code to return a meaningful error message. But I suppose the limitation will continue to exist as the API end-point itself doesn't seem to permit download of such large directories.
> 
> Could you test for a smaller repo, just to confirm that it works well where this size limit isn't exceeded?

Hello Shailesh,

I tested with a sub-subfolder containing a single file and things worked well.

Best

**Comment by Cracky5457** [comment]
Hello,

Thanks for the review I'm going to merge it and release it.

About the download limit currently we are using the default limit which is only 200mo I will talk with Marc and Paul to increase it maybe to 1gb.

We can do more but the issue is that it's consuming memory on the VM and resources.

**Comment by Cracky5457** [comment]
New version 0.4.0 is out, thanks you !

**Comment by appukuttan-shailesh** [comment]
Thanks @Cracky5457 ! Also, good to know about the imposed size limit.

**Pull request merged**
